### ISSUE TITLE
Why do you use mousemove/mouseout instead of mouseenter/mouseleave?

### ISSUE THREAD

**Issue by dilizarov** [vn38minhtran/react-tooltip-component#1]
I don't see any need to continue firing off the callbacks when you're moving within the element. For me, mousemove has resulted in some tooltips having instability/jittery effects. By using mouseenter/mouseleave, you completely bypass that because the position only gets calculated once.

Just curious if this was an important design decision. Otherwise, I'd switch the events you set up listeners on.

**Comment by minhtranite** [comment]
Fixed in commit https://github.com/vn38minhtran/react-tooltip-component/commit/47e01761654bb757426f630f34a5b76962a68985
